name: self_bill
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.4.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_dash: ^1.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_animate: ^4.2.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_bluetooth_serial:
    path: ./flutter_bluetooth_serial
  
  google_sign_in: ^6.3.0
  device_info_plus: ^11.4.0
  shared_preferences: ^2.5.3
  
  
  
  
  

  #  LOCAL PATCHED PACKAGE
  flutter_barcode_scanner:
    path: ./flutter_barcode_scanner1
  cloud_firestore: ^5.6.8
  
 
  esc_pos_utils: ^1.1.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jb-foods-header-logo-300x85.png
    - assets/grocery_line.png
    - assets/scaning_barcode.jpg
    - assets/checkout.jpg
    - assets/indiagate2.png
    - assets/logo.png
    - assets/google_icon.png
    - assets/user_default.png
