// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTBn17L_lO8gzyaugd6Eh4DJwHsI5upc',
    appId: '1:282627126373:web:23d5567cf299eda821428c',
    messagingSenderId: '282627126373',
    projectId: 'the-m-pos-app',
    authDomain: 'the-m-pos-app.firebaseapp.com',
    storageBucket: 'the-m-pos-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmVAxXu0weRCHovLrsouEcjl-liWo1_Y',
    appId: '1:282627126373:android:c1318629d928aac121428c',
    messagingSenderId: '282627126373',
    projectId: 'the-m-pos-app',
    storageBucket: 'the-m-pos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_WLj0fbDit5LOQZDBf_FzM2Hn6Y6tiM',
    appId: '1:282627126373:ios:6f7508b1b395adeb21428c',
    messagingSenderId: '282627126373',
    projectId: 'the-m-pos-app',
    storageBucket: 'the-m-pos-app.firebasestorage.app',
    iosBundleId: 'com.example.selfBill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_WLj0fbDit5LOQZDBf_FzM2Hn6Y6tiM',
    appId: '1:282627126373:ios:6f7508b1b395adeb21428c',
    messagingSenderId: '282627126373',
    projectId: 'the-m-pos-app',
    storageBucket: 'the-m-pos-app.firebasestorage.app',
    iosBundleId: 'com.example.selfBill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzTBn17L_lO8gzyaugd6Eh4DJwHsI5upc',
    appId: '1:282627126373:web:d496cf34cfd77f6021428c',
    messagingSenderId: '282627126373',
    projectId: 'the-m-pos-app',
    authDomain: 'the-m-pos-app.firebaseapp.com',
    storageBucket: 'the-m-pos-app.firebasestorage.app',
  );
}
